title: Your Blog Name
description: Short description of your blog
url: "https://eth1030.github.io"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

author:
  name: Emika Hammond
  email: eth@bu.edu

github_username: eth1030

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Projects
    url: /projects/